### PR TITLE
Install pip manually

### PR DESCRIPTION
**Pull request by fulder**
Related to PR/issue: https://github.com/ix-plugin-hub/iocage-plugin-index/pull/188 and https://www.truenas.com/community/threads/community-plugins-motioneye.91652/

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
https://github.com/ix-plugin-hub/iocage-plugin-index/blob/master/motioneye.json

Python2 package is not installed in the jail at the moment. Only python 3 is

`  "pkgs": [
        "python37",
        "py37-pip",
        "motion",
        "ffmpeg",
        "v4l-utils",
        "jpeg-turbo",
        "curl"
    ],`

**Comment by fulder** [comment]
@stephenreda there seems to be an issue with the master version of this plugin manifest after bump from python 2 -> python 3, due to motioneye not having support for 3.X :(. That's the reason for the PR (realized it was created by you, so sorry for re-writing things you already know)  in the iocage repo I linked in this PR description.

Although just downgrading back to 2.7 is also problematic as this python version has been EoL for a while and the `py27-pip` package is missing from the latest FreeBSD package repo.

I.e. this PR should be merge only if this is synced with the iocage index repo where python package can then be downgraded to python27 and the pip removed entirely. Or am I thinking wrong here?

**Comment by fulder** [comment]
Any more updates/thoughts on this? Would it be fine to merge this in and then update the plugin manifest? This plugin is broken right now so could maybe be a possible fix?

**Comment by cilix-lab** [comment]
Merged. Will test over the weekend and check manifest.

**Pull request merged**
